DROP TABLE ALLEMPLOYEES;

DROP TABLE REIMBURSEMENTS

CREATE TABLE ALLEMPLOYEES(
	EMPLOYEEID NUMBER(10) PRIMARY KEY,
	EMPLOYEETYPE varchar2(255) NOT NULL check(LENGTH(EMPLOYEETYPE) > 1),
	FIRSTNAME varchar2(255) NOT NULL check(LENGTH(FIRSTNAME) > 1),
	LASTNAME varchar2(255) NOT NULL check(LENGTH(LASTNAME) > 1),
	EMAIL varchar2(255) NOT NULL check(LENGTH(EMAIL) > 1),
	PASSWORD varchar2(255) NOT NULL check(LENGTH(PASSWORD) > 1),
	ADDRESS varchar2(255) NOT NULL check(LENGTH(ADDRESS) > 1),
	STARTDATE varchar2(255) NOT NULL check(LENGTH(STARTDATE) > 1),
	STATUS varchar2(255) NOT NULL check(LENGTH(STATUS) > 1),
);
CREATE TABLE REIMBURSEMENTS(
	REQUESTID NUMBER(10) PRIMARY KEY,
	ACNTTYPE varchar2(255) NOT NULL check(LENGTH(acntType) > 1),
	FIRSTNAME varchar2(255) NOT NULL check(LENGTH(FIRSTNAME) > 1),
	LASTNAME varchar2(255) NOT NULL check(LENGTH(LASTNAME) > 1),
	USERNAME varchar2(255) NOT NULL check(LENGTH(USERNAME) > 1),
	PASSWORD varchar2(255) NOT NULL check(LENGTH(PASSWORD) > 1),
	CONSTRAINT TRANSACTIONS_BANKACCOUNTS FOREIGN KEY (ACNTNUM_ID)
		REFERENCES BANKACCOUNTS (ACNTNUM) ON DELETE CASCADE
);