CREATE TABLE REIMBURSEMENTS(
	ACNTNUM NUMBER(10) PRIMARY KEY,
	ACNTTYPE varchar2(255) NOT NULL check(LENGTH(acntType) > 1),
	FIRSTNAME varchar2(255) NOT NULL check(LENGTH(FIRSTNAME) > 1),
	LASTNAME varchar2(255) NOT NULL check(LENGTH(LASTNAME) > 1),
	USERNAME varchar2(255) NOT NULL check(LENGTH(USERNAME) > 1),
	PASSWORD varchar2(255) NOT NULL check(LENGTH(PASSWORD) > 1),
	BALANCE DECIMAL(38, 2)
);